# Generated by Django 3.2 on 2023-02-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('name_rest', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Название ресторана')),
                ('city', models.CharField(max_length=150, verbose_name='Город')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('timezone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Часовой пояс')),
                ('is_active', models.BooleanField(default=True, verbose_name='Открыт')),
            ],
        ),
    ]
